export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  corsAllowedOrigins: process.env.CORS_ALLOWED_ORIGINS ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  revenueCatWebhookSecret: process.env.REVENUECAT_WEBHOOK_SECRET ?? "",
  revenueCatWebhookToleranceSeconds: Number(process.env.REVENUECAT_WEBHOOK_TOLERANCE_SECONDS ?? "86400"),
  rateLimitRevenueCatMax: Number(process.env.RATE_LIMIT_REVENUECAT_MAX ?? "120"),
  rateLimitRevenueCatWindowMs: Number(process.env.RATE_LIMIT_REVENUECAT_WINDOW_MS ?? "60000"),
  rateLimitUploadMax: Number(process.env.RATE_LIMIT_UPLOAD_MAX ?? "8"),
  rateLimitUploadWindowMs: Number(process.env.RATE_LIMIT_UPLOAD_WINDOW_MS ?? "60000"),
  rateLimitArtifactsMax: Number(process.env.RATE_LIMIT_ARTIFACTS_MAX ?? "20"),
  rateLimitArtifactsWindowMs: Number(process.env.RATE_LIMIT_ARTIFACTS_WINDOW_MS ?? "60000"),
  geminiApiKey: process.env.GEMINI_API_KEY ?? process.env.BUILT_IN_FORGE_API_KEY ?? "",
  geminiFastModel: process.env.GEMINI_FAST_MODEL ?? "gemini-3-flash-preview",
  geminiStrictModel: process.env.GEMINI_STRICT_MODEL ?? "gemini-3-pro-preview",
  geminiThinkingLevelFast: process.env.GEMINI_THINKING_LEVEL_FAST ?? "medium",
  geminiThinkingLevelStrict: process.env.GEMINI_THINKING_LEVEL_STRICT ?? "high",
  maxUploadMb: Number(process.env.MAX_UPLOAD_MB ?? "15"),
  maxPdfPagesOcr: Number(process.env.MAX_PDF_PAGES_OCR ?? "30"),
};
