export const ICON_SYMBOL_MAPPING = {
  "house.fill": "home",
  "paperplane.fill": "send",
  "chevron.left.forwardslash.chevron.right": "code",
  "chevron.right": "chevron-right",
  "chevron.down": "expand-more",
  "book.fill": "menu-book",
  "arrow.clockwise": "refresh",
  "person.fill": "person",
  "camera.fill": "camera-alt",
  "doc.fill": "description",
  "folder.fill": "folder",
  "clock.fill": "schedule",
  "star.fill": "star",
  "checkmark.circle.fill": "check-circle",
  "checkmark": "check",
  "xmark.circle.fill": "cancel",
  "xmark": "close",
  "gear": "settings",
  "magnifyingglass": "search",
  "plus": "add",
  "trash.fill": "delete",
  "square.and.arrow.up": "share",
  "bolt.fill": "bolt",
  "flame.fill": "local-fire-department",
  "brain": "psychology",
  "lightbulb.fill": "lightbulb",
  "questionmark.circle.fill": "help",
  "arrow.left": "arrow-back",
  "arrow.right": "arrow-forward",
  "eye.fill": "visibility",
  "lock.fill": "lock",
  "crown.fill": "workspace-premium",
  "photo.fill": "photo-library",
  "map.fill": "map",
} as const;

export type IconSymbolName = keyof typeof ICON_SYMBOL_MAPPING;
